"""add post_images table

Revision ID: 11ba398d1b1c
Revises: c8b626418a14
Create Date: 2026-03-20 20:40:07.162308

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '11ba398d1b1c'
down_revision = 'c8b626418a14'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.alter_column('background',
               existing_type=sa.TEXT(),
               type_=sa.String(length=512),
               existing_nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.alter_column('background',
               existing_type=sa.String(length=512),
               type_=sa.TEXT(),
               existing_nullable=True)

    # ### end Alembic commands ###
