"""add profile_pic to user

Revision ID: 236b7ba77e7f
Revises: 7cca2904b9d5
Create Date: 2026-04-06 12:49:48.415454

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '236b7ba77e7f'
down_revision = '7cca2904b9d5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('profile_pic', sa.String(length=512), nullable=True))
        batch_op.drop_column('profile_image')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('profile_image', sa.VARCHAR(length=255), nullable=True))
        batch_op.drop_column('profile_pic')

    # ### end Alembic commands ###
