"""Add is_admin to user (manual)

Revision ID: 8b626cb66cd2
Revises: 15f7c74abdba
Create Date: 2026-03-23 19:56:01.408048

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8b626cb66cd2'
down_revision = '15f7c74abdba'
branch_labels = None
depends_on = None


def upgrade():
    pass
# ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('is_admin', sa.Boolean(), nullable=False, server_default=sa.text('0')))
    # ### end Alembic commands ###

def downgrade():
    pass
# ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_column('is_admin')
    # ### end Alembic commands ###
